baseURL = 'https://davidtom.dev/'
languageCode = 'en-us'
title = 'David Tomczyk'
theme = 'hugo-sustain'
# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-XQ0JMFEY8W"

[params]
  avatar = "img/profile.png"
  author = "David Tomczyk"
  description = "My personal web page"

[params.social]
  Github        = "davidtom"
  Email         = "davidjtomczyk@gmail.com"
  LinkedIn      = "davidjtomczyk"
  Medium        = "davidjtomczyk"

[[menu.main]]
# name = "blog"
# weight = 100
# identifier = "blog"
#  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/dtomczyk_resume.pdf"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
# order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "production"
URL = "gs://davidtom.dev"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
